<?php
/* utf8-marker = äöüß */
$cf['security']['password']="ricomo9401";
$cf['security']['type']="wwwaut";
$cf['security']['username']="admin";
$cf['site']['template']="bahrandbahr";
$cf['language']['default']="de";
$cf['meta']['robots']="index, follow";
$cf['meta']['author']="";
$cf['meta']['publisher']="";
$cf['meta']['content-language']="de";
$cf['locator']['show_homepage']="true";
$cf['folders']['userfiles']="userfiles/";
$cf['folders']['downloads']="downloads/";
$cf['folders']['images']="images/";
$cf['backup']['numberoffiles']="5";
$cf['images']['maxsize']="150000";
$cf['downloads']['maxsize']="1000000";
$cf['mailform']['email']="zentrale@bahr-und-bahr.de";
$cf['editor']['height']="(screen.availHeight)-400";
$cf['editor']['external']="fckeditor";
$cf['menu']['color']="000000";
$cf['menu']['highlightcolor']="808080";
$cf['menu']['levels']="3";
$cf['menu']['levelcatch']="10";
$cf['menu']['sdoc']="";
$cf['menu']['legal']="CMSimple Legal Notices";
$cf['uri']['seperator']=":";
$cf['uri']['length']="200";
$cf['xhtml']['endtags']="true";
$cf['xhtml']['amp']="true";
$cf['plugins']['folder']="plugins";
$cf['functions']['file']="functions.php";
$cf['scripting']['regexp']="\#CMSimple (.*?)\#";
?>